In [31]:
import pandas as pd

In [51]:
df = pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [33]:
type(df.day[0])

str

In [34]:
df.set_index('day', inplace=True)

In [35]:
df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017           NaN        9.0   Sunny
1/5/2017          28.0        NaN    Snow
1/6/2017           NaN        7.0     NaN
1/7/2017          32.0        NaN    Rain
1/8/2017           NaN        NaN   Sunny
1/9/2017           NaN        NaN     NaN
1/10/2017         34.1        8.1  Cloudy
1/11/2017         40.0       12.0   Sunny

In [37]:
df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017           NaN        9.0   Sunny
1/5/2017          28.0        NaN    Snow
1/6/2017           NaN        7.0     NaN
1/7/2017          32.0        NaN    Rain
1/8/2017           NaN        NaN   Sunny
1/9/2017           NaN        NaN     NaN
1/10/2017         34.1        8.1  Cloudy
1/11/2017         40.0       12.0   Sunny

In [45]:
# fill numeric columns
df[["temperature", "windspeed"]] = df[["temperature", "windspeed"]].fillna(0)

# fill string column
df["event"] = df["event"].fillna("No Event")

In [46]:
df

           temperature  windspeed     event
day
1/1/2017          32.0        6.0      Rain
1/4/2017           0.0        9.0     Sunny
1/5/2017          28.0        0.0      Snow
1/6/2017           0.0        7.0  No Event
1/7/2017          32.0        0.0      Rain
1/8/2017           0.0        0.0     Sunny
1/9/2017           0.0        0.0  No Event
1/10/2017         34.1        8.1    Cloudy
1/11/2017         40.0       12.0     Sunny

In [47]:
df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.mean(),
    'event': 'No Event'
}, inplace=True)

           temperature  windspeed     event
day
1/1/2017          32.0        6.0      Rain
1/4/2017           0.0        9.0     Sunny
1/5/2017          28.0        0.0      Snow
1/6/2017           0.0        7.0  No Event
1/7/2017          32.0        0.0      Rain
1/8/2017           0.0        0.0     Sunny
1/9/2017           0.0        0.0  No Event
1/10/2017         34.1        8.1    Cloudy
1/11/2017         40.0       12.0     Sunny

In [49]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [50]:
df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.mean(),
    'event': 'No Event'
}, inplace=True)
df

         day  temperature  windspeed     event
0   1/1/2017        32.00       6.00      Rain
1   1/4/2017        33.22       9.00     Sunny
2   1/5/2017        28.00       8.42      Snow
3   1/6/2017        33.22       7.00  No Event
4   1/7/2017        32.00       8.42      Rain
5   1/8/2017        33.22       8.42     Sunny
6   1/9/2017        33.22       8.42  No Event
7  1/10/2017        34.10       8.10    Cloudy
8  1/11/2017        40.00      12.00     Sunny

In [52]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [55]:
import pandas as pd
print(pd.__version__)

3.0.2

In [56]:
df = df.ffill()

In [57]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        7.0   Sunny
6   1/9/2017         32.0        7.0   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny