In [2]:
import pandas as pd

In [3]:
df= pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv')
df.head(2)

  Datasource: Google finance Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4
0                    tickers        eps    revenue      price      people
1                      GOOGL      27.82         87        845  larry page

In [5]:
df= pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv',skiprows=1)
df.head(2)

  tickers    eps  revenue price      people
0   GOOGL  27.82       87   845  larry page
1     WMT   4.61      484    65        n.a.

In [6]:
df= pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv',header=1)
df.head(2)

  tickers    eps  revenue price      people
0   GOOGL  27.82       87   845  larry page
1     WMT   4.61      484    65        n.a.

In [4]:
df= pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv',header=1, names=["Stock_Symbol","eps","revenue","price","people"])
df.head(2)

  Stock_Symbol    eps  revenue price      people
0        GOOGL  27.82       87   845  larry page
1          WMT   4.61      484    65        n.a.

In [5]:
df= pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv',header=1,nrows=4)
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65           n.a.
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani

In [8]:
df= pd.read_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv',header=1,na_values={
    'eps':['not available'],
    'revenue':[-1],
    'people':['not available','n.a.']
})
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [17]:
df = pd.read_csv(
    r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\stock_data.csv',
    header=1,
    na_values=['Not available', 'not available', 'N/A', 'n.a.', -1]
)

In [18]:
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [19]:

df["pe"] = df["price"] / df["eps"]
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [22]:
df.to_csv(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\pe1.csv')

In [25]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [29]:


df_movies = pd.read_excel(
    r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\movies_db.xlsx',
    sheet_name="movies"
)

df_movies.head(3)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5

In [30]:

df_financials = pd.read_excel(
    r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\movies_db.xlsx',
    sheet_name="financials"
)

df_financials.head(3)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$

In [31]:
df_merged = pd.merge(df_movies, df_financials, on="movie_id")
df_merged.head(3)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,$$

In [32]:
df_merged.to_excel(r'C:\Users\Shushma Thatipamula\Python_Learnings\Python_Learnings\datasource\movies_merged.xlsx', sheet_name="Sheet1", index=False)

In [33]:
df_stocks= pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price':[845, 65, 64],
    'pe':[30.45, 14.27, 30.97],
    'eps':[27.82, 4.61, 2.12]
})

In [34]:
df_stocks

  tickers  price     pe    eps
0   GOOGL    845  30.45  27.82
1     WMT     65  14.27   4.61
2    MSFT     64  30.97   2.12